version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region ${AWS_DEFAULT_REGION} --no-include-email)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)
      - IMAGE_URI="${REPOSITORY_URI}:${IMAGE_TAG}"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo $BitNodeToken
      - docker build --build-arg BIT_NODE_TOKEN=$BitNodeToken -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '[{"name":"${CustomContainerName}","imageUri":"%s"}]' "$IMAGE_URI" > images.json
artifacts:
  files: images.json
#   base-directory: build
