---
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Cluster:
    Type: String

  Service:
    Type: String

Resources:
  CodeDeploy:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: ${AWS::StackName}-CodeDeployApplication
      ComputePlatform: ECS

  CodeDeployRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codedeploy.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /service-role/
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ecs:DescribeServices,
                  - ecs:CreateTaskSet,
                  - ecs:UpdateServicePrimaryTaskSet,
                  - ecs:DeleteTaskSet,
                  - elasticloadbalancing:DescribeTargetGroups,
                  - elasticloadbalancing:DescribeListeners,
                  - elasticloadbalancing:ModifyListener,
                  - elasticloadbalancing:DescribeRules,
                  - elasticloadbalancing:ModifyRule,
                  - lambda:InvokeFunction,
                  - cloudwatch:DescribeAlarms,
                  - sns:Publish,
                  - s3:GetObject,
                  - s3:GetObjectVersion
                Resource: *
              - Effect: Allow
                Action: 
                  - iam:PassRole
                Resource: *
                Condition: 
                  StringLike: 
                    iam:PassedToService:
                      - ecs-tasks.amazonaws.com

  CodeDeployDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ServiceRoleArn: !Fn::GetAtt CodeDeployRole.Arn